version: '3.8'

services:
  whatsapp-mcp:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - whatsapp_data:/app/store
      - whatsapp_media:/app/media
    environment:
      - BRIDGE_HOST=0.0.0.0
      - BRIDGE_PORT=3000
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      - SQLITE_PATH=/app/store
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  whatsapp_data:
    driver: local
  whatsapp_media:
    driver: local
